import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

import Squares from "./components/Squares/Squares";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "aiWy4wQrsuQSK0pwE-mulYmOMGoIaKD-ex6x1110cAw",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute top-0 right-0 left-0 bottom-0 w-full h-full -z-10">
          <Squares 
            speed={0.5} 
            squareSize={40}
            direction='diagonal' // up, down, left, right, diagonal
            borderColor='var(--color-accent-1)'
            hoverFillColor='var(--color-accent-2)'
          />
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
